services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.database:/var/lib/postgresql/data
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    entrypoint: /bin/bash

  test:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTEST_ADDOPTS="--cov=stuart --cov-report=term-missing"
    command: poetry run pytest

  lint:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: >
      sh -c "poetry run ruff check . &&
             poetry run black . --check &&
             poetry run mypy ."